export type VideoItem = { title: string; url: string };
export type VideoCategory = {
  id: string;
  name: string;
  type: "video" | "links" | "profile";
  items: VideoItem[];
};

export const videoCategories: VideoCategory[] = [
  {
    id: "l1",
    name: "L1",
    type: "video",
    items: [
      { title: "Analyse de circuit à semi-conducteur", url: "https://youtube.com/playlist?list=PL3FwHB34wY1NczLrODKgy3tVQOEkeoU8D&si=EwyHPGjTs8rubAck" },
      { title: "Algorithme exercices", url: "https://youtube.com/playlist?list=PLLXxbxMwpPFmFvx9q-JEOs8vUbhb2eHLb&si=vlAd9UB0ZzFF9UVq" },
      { title: "Circuits combinatoires", url: "https://youtube.com/playlist?list=PLUfAL3A5C7Tvcae1zgeOqFAO8WK2kS1Z4&si=XgwKZjVfEd7U31WM" },
      { title: "Exercices corrigés pour apprendre l'algorithmique (Darija)", url: "https://www.youtube.com/playlist?list=PLZpzLuUp9qXzOgDakYP0UAGIBNk0pPdvZ" },
      { title: "Algorithmes - الخوارزميات", url: "https://www.youtube.com/playlist?list=PLZpzLuUp9qXwrApSukhtvpi4U6l-INcTI" },
      { title: "Physique 1 pour les L1", url: "https://www.youtube.com/playlist?list=PLUwv-LDWJDmsU9imgg16KB00PU0ozbAr-" },
      { title: "المصفوفات", url: "https://youtube.com/playlist?list=PLXkV3hT6vW-IcQSVQCycVbEq_VS1_LRq6&si=FJoGd_DWyOCi0Q_s" },
      { title: "Composant électronique et systèmes", url: "https://www.youtube.com/playlist?list=PLaCO3rRZnI7UoDxIF0XMlZXVHT58Q57LR" },
    ],
  },
  {
    id: "l2",
    name: "L2",
    type: "video",
    items: [
      { title: "POO - Playlist 1", url: "https://youtube.com/playlist?list=PLKV6WevXj-lU7FaGE7hnijGQmjtcFSWpk" },
      { title: "Java (OOP)", url: "https://youtube.com/playlist?list=PLCInYL3l2AajYlZGzU_LVrHdoouf8W6ZN" },
      { title: "C# - Playlist", url: "https://youtube.com/playlist?list=PLKV6WevXj-lUrK1bPvO5qL2ZjKl2PjOTG" },
      { title: "POO - Playlist 2", url: "https://youtube.com/playlist?list=PLuXY3ddo_8nzUrgCyaX_WEIJljx_We-c1" },
      { title: "Analyse Numérique", url: "https://youtube.com/playlist?list=PLXHo2PMldglk7QytzdSLTuRCUE2F7f3yQ" },
      { title: "Logique Mathématique", url: "https://youtube.com/playlist?list=PLFN8GW4Q3m3-jLcZAga1rjDs8qaTH6QB9" },
      { title: "Algorithmique - Playlist 1", url: "https://youtube.com/playlist?list=PLCInYL3l2AajqOUW_2SwjWeMwf4vL4RSp" },
      { title: "Algorithmique - Playlist 2", url: "https://youtube.com/playlist?list=PLz8b0eOENotrnOvZt0305CYF627nFvxW7" },
      { title: "Architecture - Cours 1", url: "https://youtu.be/lkSd3U7GjvE" },
      { title: "Architecture - Cours 2", url: "https://youtu.be/1CphPAqfKc8" },
      { title: "Système d'information - Playlist 1", url: "https://youtube.com/playlist?list=PLirv9XJLkgiVA4dibkwN8GuxERLhdWs93" },
      { title: "Système d'information - Playlist 2", url: "https://youtube.com/playlist?list=PLnZB721E4l395Fekgz8fc7_vHjUumiQes&si=iVeQR8yl6VGLXb5B" },
      { title: "Système d'information - Playlist 3", url: "https://youtube.com/playlist?list=PLJe5vGB_oTirJ2w8Ey9mIptmgtFMnINKw&si=qS_JV4_oGo8G_0zS" },
      { title: "Théorie des Graphes - Playlist 1", url: "https://youtube.com/playlist?list=PLEUfg7A8gGzrAPJJjBR3DGylHXGogNA_l" },
      { title: "Théorie des Graphes - Cours", url: "https://youtu.be/89Hb7sjBIjk" },
      { title: "Base de Données - Cours 1", url: "https://youtube.com/playlist?list=PLwnZV6J_uhj0_kxsBd4-IrWNxJECoy_Ha" },
      { title: "Base de Données - Cours 2", url: "https://youtube.com/playlist?list=PL1zcP88W0NZtSCFojm4sMohFc2QiA-O-i" },
      { title: "Base de Données - TPS (SQL)", url: "https://youtube.com/playlist?list=PLt0HRIA9i35u3gO_8m8C-fhTEjPJQ7dr_" },
      { title: "Réseaux - Cours", url: "https://youtube.com/playlist?list=PLh330TDu4_HAye58MbG6Yto0MDEAd9Icp" },
      { title: "Réseaux - TPS (CISCO)", url: "https://youtube.com/playlist?list=PLdtOYS9ml58Oij_qwpvrcBtPvvSOKeFRk" },
      { title: "Systèmes d'exploitation - Cours", url: "https://youtu.be/3EwlUKMaOS4" },
      { title: "Dev Web - Elzero", url: "https://youtube.com/c/ElzeroInfo" },
      { title: "THL - Playlist", url: "https://youtube.com/playlist?list=PLN8d-2cTVrvZL4Ax6NRGzlDZ45YJQkEC1" },
      { title: "INF2 - Réseaux", url: "https://youtube.com/playlist?list=PLDUBCXV-C1hrYwKeG_7u5NlQK1HUcn7yH" },
      { title: "INF2 - Systèmes d'exploitation", url: "https://youtube.com/playlist?list=PLHKTPL-jkzUqgHIBdC2I16QqZCSDN_6oS" },
      { title: "INF2 - Base de Données", url: "https://youtube.com/playlist?list=PL-b5Zp9H7qBheh2GuX6_iV7UJjjb3VGDr" },
      { title: "INF2 - THL (Cours)", url: "https://youtube.com/playlist?list=PLqktoQpXXG5CRtjQ97z0z8cAMRfR7bbaM" },
      { title: "INF2 - THL (Exercices)", url: "https://youtube.com/playlist?list=PLlnWZI5J2hBC4NPC8criiqgLuaSY6SpiZ" },
      { title: "Dev Web - HTML", url: "https://youtu.be/q3yFo-t1ykw" },
      { title: "Dev Web - CSS", url: "https://youtu.be/Z-5QVutAEW4" },
      { title: "Dev Web - PHP", url: "https://youtu.be/pszZMzI9a7A" },
      { title: "Dev Web - JavaScript", url: "https://youtube.com/playlist?list=PLDoPjvoNmBAw6p0z0Ek0OjPzeXoqlFlCh" },
      { title: "POO - Playlist 3", url: "https://youtube.com/playlist?list=PL1DUmTEdeA6K7rdxKiWJq6JIxTvHalY8f" },
      { title: "POO - Playlist 4", url: "https://youtube.com/playlist?list=PL1DUmTEdeA6Icttz-O9C3RPRF8R8Px5vk" },
    ],
  },
  {
    id: "l3",
    name: "L3",
    type: "video",
    items: [
      { title: "système d'exploitation 2", url: "https://youtube.com/playlist?list=PL4hYmILIgND4vdbJqJpVIjTic0FHNk-jt&si=DAKUkI0knri88ZA3" },
      { title: "Le système d'exploitation", url: "https://youtube.com/playlist?list=PLiS1ejpMEwB5CsFKib_iS911_bbzHugcA&si=v-wZMrmHWhZnog9c" },
      { title: "operating systems 2 - نظم تشغيل", url: "https://youtube.com/playlist?list=PL60rTvwmJG022aOyqyRS9hYmMI8g9ZCht&si=iTNI-8Cty0KSMEfj" },
      { title: "PROGRAMMATION LINEAIRE", url: "https://youtube.com/playlist?list=PLXsM8C1n7ImMvoqSJXKjH7QpnM8LYlLmy&si=WYSR3k5qX79CD9c0" },
      { title: "Probabilités", url: "https://youtube.com/playlist?list=PLCB2plBhwI7e-CjJyzN_UTm9rWyN3ykVP&si=b4GONzRB7hum0JVt" },
      { title: "Probabilités (Sup)", url: "https://youtube.com/playlist?list=PLlaFpJcuzvllMcU6DLqNr-7s2HxeplpC3&si=0YhyTSeis3o9Rbf4" },
      { title: "احصاء و احتمالات", url: "https://youtube.com/playlist?list=PL60rTvwmJG01FV2Pqgn1Cw2esJ8oejAJV&si=htafg8TKjJnuQgv5" },
      { title: "Compilation", url: "https://youtube.com/playlist?list=PLpnxtvhKFSYcdmRkaW9rJhKAaGzZuSJw0&si=g7i9RvWUPzeJzd9w" },
      { title: "COMPILATION 2", url: "https://youtube.com/playlist?list=PLSENmhglzJjRNT4RlXr8lB9LbZjcB2Wgl&si=LE7poOsk1ZwqLYf8" },
      { title: "compilation 3", url: "https://youtube.com/playlist?list=PLS6wYe_OqRAPJ8bUHH3kq7UbPll5hLvR1&si=b_iuvwr9GTt_dNkf" },
      { title: "Cours compilation", url: "https://youtube.com/playlist?list=PLCp87s2gFzMvGXMcVsw-LbLSK7bm-OOsO&si=FwZa02QJxnLA_IIH" },
      { title: "Compiler Design - بناء المترجمات", url: "https://youtube.com/playlist?list=PL60rTvwmJG00AL2Af99zvFdi0WO8dWHys&si=_729OLaTIejCjFo6" },
      { title: "IHM VIDEOS BY TEACHER", url: "https://youtube.com/playlist?list=PLEf5-yZk3HXS8lyW4yUldI8y-anH4o-46&si=wcBH69fHS3FLBj7u" },
      { title: "L1 - Genie Logiciel", url: "https://youtube.com/playlist?list=PLe_asaE0nbPbnuAztjQyN4Qth-2EIe0-m&si=0eblClePAd9l73RV" },
      { title: "Genie logiciel", url: "https://youtube.com/playlist?list=PLSENmhglzJjRo7ziNTHkAq9YTezFxtYob&si=dIkLpFp1DH52sFUI" },
      { title: "Génie Logiciel 2", url: "https://youtube.com/playlist?list=PLQyCQ7CblbzFgIsYqB7wXQxrqcWyylFxc&si=unMqDQE5B-8YwKwT" },
      { title: "genie logiciel 3", url: "https://youtube.com/playlist?list=PL9czQr4kJeMVVLLRzWP_bQ3wtoXUdR_UG&si=O3eqfPJP0AJ73pRT" },
      { title: "TP Génie Logiciel", url: "https://youtube.com/playlist?list=PLiYyv-5mWgyjIVuXggDMv__SjDlFWu0Tj&si=rYdlivMFxYWYL3Di" },
      { title: "Génie Logiciel 4", url: "https://youtube.com/playlist?list=PLBWD3LpmoU7EE-I3f_AHM6BW9s6Qwj4jc&si=V5uEj3F-4W15oaj-" },
      { title: "Génie logiciel 5", url: "https://youtube.com/playlist?list=PLNYRJqr01g92E33uWM293GO__cvECuiGr&si=gdNJvkqnbxi8lW0i" },
      { title: "GL", url: "https://youtube.com/playlist?list=PLYxEHINSaRSjaCv5EMh72i0JrDSe0X5oL&si=0-fHUsVG2Ampw_dB" },
      { title: "ihm", url: "https://youtube.com/playlist?list=PLwHR0KRrbCd4i_1ejS_4S93Af04vv68UG&si=hfvjqOgUDvPRRhbj" },
      { title: "INTERFACES HOMME-MACHINE (IHM)", url: "https://youtube.com/playlist?list=PL6kS__I97mDwB0TlT-vd4qOaVFYoGGymZ&si=vQiNinIUQK5_vR-n" },
      { title: "Principes d'orgonomie IHM univ M'sila", url: "https://youtube.com/playlist?list=PLBBIn272C110FddhP-UZJTVbPbhcQocoP&si=JXZO7qJkJ4jmgBI8" },
      { title: "TP IHM", url: "https://youtube.com/playlist?list=PLiYyv-5mWgyjfrwAtseWHAVWeFYOBkn9R&si=LS0Dxv8-OpPtOfnd" },
    ],
  },
  { id: "m1", name: "M1", type: "video", items: [] },
  { id: "m2", name: "M2", type: "video", items: [] },
  { id: "ingenieurs", name: "Ingénieurs", type: "video", items: [] },
  {
    id: "autres",
    name: "Autres Links",
    type: "links",
    items: [
      { title: "Physique Chimie Math Biologie", url: "https://www.physiquechimiemathbiologie.com/?m=1" },
      { title: "Tresor CSE Club", url: "https://tresor.cse.club/" },
      { title: "Telegram L3 ISIL/SI", url: "https://t.me/l3isil_si" },
      { title: "Telegram L1", url: "https://t.me/l1informatique" },
      { title: "Telegram L2", url: "https://t.me/l2informatique" },
      { title: "Telegram Master 1", url: "https://t.me/master1info" },
    ],
  },
  {
    id: "profile",
    name: "Profile",
    type: "profile",
    items: [
      { title: "@ELOUARDIMohamed", url: "https://www.youtube.com/@ELOUARDIMohamed?si=jLK7oSgGVJNAyxqd&fbclid=PAAaYVvOgHppPfbOvqwnJS6qcMZVIEMr6jPkkYRHQ6jyYsXgAZN9MIc28PnnI" },
      { title: "@mcemeftah", url: "https://www.youtube.com/@mcemeftah?si=ZODF2I-GJUJJohuW&fbclid=PAAabRPIhn0s7nJYblCOw01ySk7lImRUhxCLQa89k1nOUFimBlFy10ejTTwxI" },
      { title: "@csplus", url: "https://www.youtube.com/@csplus?si=l5sXVR_sZHZTZLgP&fbclid=PAAaZQTvVQKJIkWZcUauXsyXG5bcSY11imeGEhY4On9_diB6Ut05Ng37xhIcw" },
      { title: "@Mahseur", url: "https://www.youtube.com/@Mahseur?si=mi-ZaEz24TYO-ZIU&fbclid=PAAaZwC_Nm_hcl_yoPu_JulX-ak4VXUVkthIvFHpmST02SmvTnfDcJ01RxOyc" },
      { title: "@AYMENDEV", url: "https://www.youtube.com/@AYMENDEV?si=ddNqm3YjMdbiA6s4&fbclid=PAAaYuMgaiegEDZavFh4vqejRckoTOWzm7utld-WigXAoGteVjPUc9bZ0b6o0" },
      { title: "@umath", url: "https://www.youtube.com/@umath?si=DUG6AP9C_AeAD4j7&fbclid=PAAaaLvbLVryeuyPrJWfLbZjc5PAk9II5ParnAP3nsCq2E8gNOzCH-GpJnlhw" },
      { title: "@asmakf", url: "https://www.youtube.com/@asmakf?si=M-n0e6o-kgZkBZ4D&fbclid=PAAaaZH5OvuiWKJZiBPhxa4cvVsACSDPwVZQiM3RY002Z6EJYqAtCeclSgVoM" },
      { title: "@15MinMathLr", url: "https://www.youtube.com/@15MinMathLr?si=2cHLl9hfeULQm-nk&fbclid=PAAaZ0jyc8uWgC5M_GpflsPRVmRk5Gi_wRWi_cKd4xwMxFwY-WKVekkJi7x6Q" },
    ],
  },
];
